#api call for list all doctors
###
GET http://127.0.0.1:8000/doctors/
Accept: application/json

#api call for adding doctor
###
POST http://127.0.0.1:8000/doctors/
Content-Type: application/json

{
    "name":"Anu",
    "specialization":"General Medicine / Internal Medicine",
    "fee":350,
    "qualification":"MBBS",
    "email":"anu03@gmail.com"
}

#api call for fetch doctor
###
GET http://127.0.0.1:8000/doctors/3/
Accept: application/json

#api call for update doctor
###
PUT http://127.0.0.1:8000/doctors/3/
Content-Type: application/json

{
    "id":3,
    "name":"sreekumar",
    "specialization":"radiology",
    "fee":400,
    "qualification":"MBBS,MD",
    "email":"sreekumar123@gmail.com"
}

#api call for delete doctor
###
DELETE http://127.0.0.1:8000/doctors/5/
Accept: application/json

#v2 endpoints
#api call for list all doctors
###
GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json

#api call for adding doctor
###
POST http://127.0.0.1:8000/v2/doctors/
Content-Type: application/json

{
    "name":"George",
    "specialization":"cardiology",
    "fee":350,
    "qualification":"MBBS",
    "email":"george@gmail.com"
}

#api call for fetch doctor
###
GET http://127.0.0.1:8000/v2/doctors/3/
Accept: application/json

#api call for update doctor
###
PUT http://127.0.0.1:8000/v2/doctors/3/
Content-Type: application/json

{
  "id": 2,
  "name": "Arun Kumar",
  "specialization": "dermatology",
  "fee":300,
  "qualification": "MBBS",
  "email": "arun8@gmail.com"
}

#api call for delete doctor
###
DELETE http://127.0.0.1:8000/v2/doctors/7/
Accept: application/json

#api call for create admin
###
POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{
    "username":"superuser",
    "email":"superuser@gmail.com",
    "password":"superuser"
}
